source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KPCRotateWalkthrough_Example', :exclusive => true do
  pod 'KPCRotateWalkthrough', :path => '../'
end

target 'KPCRotateWalkthrough_Tests', :exclusive => true do
  pod 'KPCRotateWalkthrough', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
